SELECT
    *
    ,LAG(active_quarter, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS active_quarter_lag_6
    ,LAG(cliente_vip, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cliente_vip_lag_6
    ,LAG(internet, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS internet_lag_6
    ,LAG(cliente_edad, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cliente_edad_lag_6
    ,LAG(cliente_antiguedad, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cliente_antiguedad_lag_6
    ,LAG(mrentabilidad, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mrentabilidad_lag_6
    ,LAG(mrentabilidad_annual, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mrentabilidad_annual_lag_6
    ,LAG(mcomisiones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcomisiones_lag_6
    ,LAG(mactivos_margen, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mactivos_margen_lag_6
    ,LAG(mpasivos_margen, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpasivos_margen_lag_6
    ,LAG(cproductos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cproductos_lag_6
    ,LAG(tcuentas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS tcuentas_lag_6
    ,LAG(ccuenta_corriente, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccuenta_corriente_lag_6
    ,LAG(mcuenta_corriente_adicional, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcuenta_corriente_adicional_lag_6
    ,LAG(mcuenta_corriente, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcuenta_corriente_lag_6
    ,LAG(ccaja_ahorro, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccaja_ahorro_lag_6
    ,LAG(mcaja_ahorro, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcaja_ahorro_lag_6
    ,LAG(mcaja_ahorro_adicional, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcaja_ahorro_adicional_lag_6
    ,LAG(mcaja_ahorro_dolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcaja_ahorro_dolares_lag_6
    ,LAG(cdescubierto_preacordado, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cdescubierto_preacordado_lag_6
    ,LAG(mcuentas_saldo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcuentas_saldo_lag_6
    ,LAG(ctarjeta_debito, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_debito_lag_6
    ,LAG(ctarjeta_debito_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_debito_transacciones_lag_6
    ,LAG(mautoservicio, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mautoservicio_lag_6
    ,LAG(ctarjeta_visa, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_visa_lag_6
    ,LAG(ctarjeta_visa_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_visa_transacciones_lag_6
    ,LAG(mtarjeta_visa_consumo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtarjeta_visa_consumo_lag_6
    ,LAG(ctarjeta_master, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_master_lag_6
    ,LAG(ctarjeta_master_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_master_transacciones_lag_6
    ,LAG(mtarjeta_master_consumo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtarjeta_master_consumo_lag_6
    ,LAG(cprestamos_personales, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cprestamos_personales_lag_6
    ,LAG(mprestamos_personales, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mprestamos_personales_lag_6
    ,LAG(cprestamos_prendarios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cprestamos_prendarios_lag_6
    ,LAG(mprestamos_prendarios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mprestamos_prendarios_lag_6
    ,LAG(cprestamos_hipotecarios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cprestamos_hipotecarios_lag_6
    ,LAG(mprestamos_hipotecarios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mprestamos_hipotecarios_lag_6
    ,LAG(cplazo_fijo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cplazo_fijo_lag_6
    ,LAG(mplazo_fijo_dolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mplazo_fijo_dolares_lag_6
    ,LAG(mplazo_fijo_pesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mplazo_fijo_pesos_lag_6
    ,LAG(cinversion1, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cinversion1_lag_6
    ,LAG(minversion1_pesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS minversion1_pesos_lag_6
    ,LAG(minversion1_dolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS minversion1_dolares_lag_6
    ,LAG(cinversion2, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cinversion2_lag_6
    ,LAG(minversion2, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS minversion2_lag_6
    ,LAG(cseguro_vida, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cseguro_vida_lag_6
    ,LAG(cseguro_auto, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cseguro_auto_lag_6
    ,LAG(cseguro_vivienda, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cseguro_vivienda_lag_6
    ,LAG(cseguro_accidentes_personales, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cseguro_accidentes_personales_lag_6
    ,LAG(ccaja_seguridad, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccaja_seguridad_lag_6
    ,LAG(cpayroll_trx, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cpayroll_trx_lag_6
    ,LAG(mpayroll, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpayroll_lag_6
    ,LAG(mpayroll2, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpayroll2_lag_6
    ,LAG(cpayroll2_trx, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cpayroll2_trx_lag_6
    ,LAG(ccuenta_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccuenta_debitos_automaticos_lag_6
    ,LAG(mcuenta_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcuenta_debitos_automaticos_lag_6
    ,LAG(ctarjeta_visa_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_visa_debitos_automaticos_lag_6
    ,LAG(mttarjeta_visa_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mttarjeta_visa_debitos_automaticos_lag_6
    ,LAG(ctarjeta_master_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_master_debitos_automaticos_lag_6
    ,LAG(mttarjeta_master_debitos_automaticos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mttarjeta_master_debitos_automaticos_lag_6
    ,LAG(cpagodeservicios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cpagodeservicios_lag_6
    ,LAG(mpagodeservicios, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpagodeservicios_lag_6
    ,LAG(cpagomiscuentas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cpagomiscuentas_lag_6
    ,LAG(mpagomiscuentas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpagomiscuentas_lag_6
    ,LAG(ccajeros_propios_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajeros_propios_descuentos_lag_6
    ,LAG(mcajeros_propios_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcajeros_propios_descuentos_lag_6
    ,LAG(ctarjeta_visa_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_visa_descuentos_lag_6
    ,LAG(mtarjeta_visa_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtarjeta_visa_descuentos_lag_6
    ,LAG(ctarjeta_master_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_master_descuentos_lag_6
    ,LAG(mtarjeta_master_descuentos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtarjeta_master_descuentos_lag_6
    ,LAG(ccomisiones_mantenimiento, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccomisiones_mantenimiento_lag_6
    ,LAG(mcomisiones_mantenimiento, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcomisiones_mantenimiento_lag_6
    ,LAG(ccomisiones_otras, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccomisiones_otras_lag_6
    ,LAG(mcomisiones_otras, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcomisiones_otras_lag_6
    ,LAG(cforex, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cforex_lag_6
    ,LAG(cforex_buy, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cforex_buy_lag_6
    ,LAG(mforex_buy, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mforex_buy_lag_6
    ,LAG(cforex_sell, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cforex_sell_lag_6
    ,LAG(mforex_sell, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mforex_sell_lag_6
    ,LAG(ctransferencias_recibidas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctransferencias_recibidas_lag_6
    ,LAG(mtransferencias_recibidas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtransferencias_recibidas_lag_6
    ,LAG(ctransferencias_emitidas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctransferencias_emitidas_lag_6
    ,LAG(mtransferencias_emitidas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtransferencias_emitidas_lag_6
    ,LAG(cextraccion_autoservicio, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cextraccion_autoservicio_lag_6
    ,LAG(mextraccion_autoservicio, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mextraccion_autoservicio_lag_6
    ,LAG(ccheques_depositados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccheques_depositados_lag_6
    ,LAG(mcheques_depositados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcheques_depositados_lag_6
    ,LAG(ccheques_emitidos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccheques_emitidos_lag_6
    ,LAG(mcheques_emitidos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcheques_emitidos_lag_6
    ,LAG(ccheques_depositados_rechazados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccheques_depositados_rechazados_lag_6
    ,LAG(mcheques_depositados_rechazados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcheques_depositados_rechazados_lag_6
    ,LAG(ccheques_emitidos_rechazados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccheques_emitidos_rechazados_lag_6
    ,LAG(mcheques_emitidos_rechazados, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcheques_emitidos_rechazados_lag_6
    ,LAG(tcallcenter, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS tcallcenter_lag_6
    ,LAG(ccallcenter_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccallcenter_transacciones_lag_6
    ,LAG(thomebanking, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS thomebanking_lag_6
    ,LAG(chomebanking_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS chomebanking_transacciones_lag_6
    ,LAG(ccajas_transacciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_transacciones_lag_6
    ,LAG(ccajas_consultas, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_consultas_lag_6
    ,LAG(ccajas_depositos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_depositos_lag_6
    ,LAG(ccajas_extracciones, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_extracciones_lag_6
    ,LAG(ccajas_otras, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_otras_lag_6
    ,LAG(catm_trx, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS catm_trx_lag_6
    ,LAG(matm, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS matm_lag_6
    ,LAG(catm_trx_other, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS catm_trx_other_lag_6
    ,LAG(matm_other, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS matm_other_lag_6
    ,LAG(ctrx_quarter, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctrx_quarter_lag_6
    ,LAG(tmobile_app, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS tmobile_app_lag_6
    ,LAG(cmobile_app_trx, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cmobile_app_trx_lag_6
    ,LAG(Master_delinquency, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_delinquency_lag_6
    ,LAG(Master_status, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_status_lag_6
    ,LAG(Master_mfinanciacion_limite, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mfinanciacion_limite_lag_6
    ,LAG(Master_Fvencimiento, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_Fvencimiento_lag_6
    ,LAG(Master_Finiciomora, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_Finiciomora_lag_6
    ,LAG(Master_msaldototal, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_msaldototal_lag_6
    ,LAG(Master_msaldopesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_msaldopesos_lag_6
    ,LAG(Master_msaldodolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_msaldodolares_lag_6
    ,LAG(Master_mconsumospesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mconsumospesos_lag_6
    ,LAG(Master_mconsumosdolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mconsumosdolares_lag_6
    ,LAG(Master_mlimitecompra, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mlimitecompra_lag_6
    ,LAG(Master_madelantopesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_madelantopesos_lag_6
    ,LAG(Master_madelantodolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_madelantodolares_lag_6
    ,LAG(Master_fultimo_cierre, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_fultimo_cierre_lag_6
    ,LAG(Master_mpagado, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mpagado_lag_6
    ,LAG(Master_mpagospesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mpagospesos_lag_6
    ,LAG(Master_mpagosdolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mpagosdolares_lag_6
    ,LAG(Master_fechaalta, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_fechaalta_lag_6
    ,LAG(Master_mconsumototal, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mconsumototal_lag_6
    ,LAG(Master_cconsumos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_cconsumos_lag_6
    ,LAG(Master_cadelantosefectivo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_cadelantosefectivo_lag_6
    ,LAG(Master_mpagominimo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mpagominimo_lag_6
    ,LAG(Visa_delinquency, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_delinquency_lag_6
    ,LAG(Visa_status, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_status_lag_6
    ,LAG(Visa_mfinanciacion_limite, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mfinanciacion_limite_lag_6
    ,LAG(Visa_Fvencimiento, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_Fvencimiento_lag_6
    ,LAG(Visa_Finiciomora, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_Finiciomora_lag_6
    ,LAG(Visa_msaldototal, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_msaldototal_lag_6
    ,LAG(Visa_msaldopesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_msaldopesos_lag_6
    ,LAG(Visa_msaldodolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_msaldodolares_lag_6
    ,LAG(Visa_mconsumospesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mconsumospesos_lag_6
    ,LAG(Visa_mconsumosdolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mconsumosdolares_lag_6
    ,LAG(Visa_mlimitecompra, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mlimitecompra_lag_6
    ,LAG(Visa_madelantopesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_madelantopesos_lag_6
    ,LAG(Visa_madelantodolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_madelantodolares_lag_6
    ,LAG(Visa_fultimo_cierre, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_fultimo_cierre_lag_6
    ,LAG(Visa_mpagado, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mpagado_lag_6
    ,LAG(Visa_mpagospesos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mpagospesos_lag_6
    ,LAG(Visa_mpagosdolares, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mpagosdolares_lag_6
    ,LAG(Visa_fechaalta, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_fechaalta_lag_6
    ,LAG(Visa_mconsumototal, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mconsumototal_lag_6
    ,LAG(Visa_cconsumos, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_cconsumos_lag_6
    ,LAG(Visa_cadelantosefectivo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_cadelantosefectivo_lag_6
    ,LAG(Visa_mpagominimo, 6) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mpagominimo_lag_6
FROM competencia_03
