SELECT
    *
    ,LAG(active_quarter, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS active_quarter_lag_3
    ,LAG(cliente_vip, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cliente_vip_lag_3
    ,LAG(internet, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS internet_lag_3
    ,LAG(cliente_edad, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cliente_edad_lag_3
    ,LAG(cliente_antiguedad, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cliente_antiguedad_lag_3
    ,LAG(mrentabilidad, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mrentabilidad_lag_3
    ,LAG(mrentabilidad_annual, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mrentabilidad_annual_lag_3
    ,LAG(mcomisiones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcomisiones_lag_3
    ,LAG(mactivos_margen, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mactivos_margen_lag_3
    ,LAG(mpasivos_margen, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpasivos_margen_lag_3
    ,LAG(cproductos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cproductos_lag_3
    ,LAG(tcuentas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS tcuentas_lag_3
    ,LAG(ccuenta_corriente, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccuenta_corriente_lag_3
    ,LAG(mcuenta_corriente_adicional, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcuenta_corriente_adicional_lag_3
    ,LAG(mcuenta_corriente, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcuenta_corriente_lag_3
    ,LAG(ccaja_ahorro, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccaja_ahorro_lag_3
    ,LAG(mcaja_ahorro, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcaja_ahorro_lag_3
    ,LAG(mcaja_ahorro_adicional, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcaja_ahorro_adicional_lag_3
    ,LAG(mcaja_ahorro_dolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcaja_ahorro_dolares_lag_3
    ,LAG(cdescubierto_preacordado, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cdescubierto_preacordado_lag_3
    ,LAG(mcuentas_saldo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcuentas_saldo_lag_3
    ,LAG(ctarjeta_debito, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_debito_lag_3
    ,LAG(ctarjeta_debito_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_debito_transacciones_lag_3
    ,LAG(mautoservicio, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mautoservicio_lag_3
    ,LAG(ctarjeta_visa, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_visa_lag_3
    ,LAG(ctarjeta_visa_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_visa_transacciones_lag_3
    ,LAG(mtarjeta_visa_consumo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtarjeta_visa_consumo_lag_3
    ,LAG(ctarjeta_master, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_master_lag_3
    ,LAG(ctarjeta_master_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_master_transacciones_lag_3
    ,LAG(mtarjeta_master_consumo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtarjeta_master_consumo_lag_3
    ,LAG(cprestamos_personales, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cprestamos_personales_lag_3
    ,LAG(mprestamos_personales, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mprestamos_personales_lag_3
    ,LAG(cprestamos_prendarios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cprestamos_prendarios_lag_3
    ,LAG(mprestamos_prendarios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mprestamos_prendarios_lag_3
    ,LAG(cprestamos_hipotecarios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cprestamos_hipotecarios_lag_3
    ,LAG(mprestamos_hipotecarios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mprestamos_hipotecarios_lag_3
    ,LAG(cplazo_fijo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cplazo_fijo_lag_3
    ,LAG(mplazo_fijo_dolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mplazo_fijo_dolares_lag_3
    ,LAG(mplazo_fijo_pesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mplazo_fijo_pesos_lag_3
    ,LAG(cinversion1, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cinversion1_lag_3
    ,LAG(minversion1_pesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS minversion1_pesos_lag_3
    ,LAG(minversion1_dolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS minversion1_dolares_lag_3
    ,LAG(cinversion2, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cinversion2_lag_3
    ,LAG(minversion2, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS minversion2_lag_3
    ,LAG(cseguro_vida, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cseguro_vida_lag_3
    ,LAG(cseguro_auto, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cseguro_auto_lag_3
    ,LAG(cseguro_vivienda, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cseguro_vivienda_lag_3
    ,LAG(cseguro_accidentes_personales, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cseguro_accidentes_personales_lag_3
    ,LAG(ccaja_seguridad, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccaja_seguridad_lag_3
    ,LAG(cpayroll_trx, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cpayroll_trx_lag_3
    ,LAG(mpayroll, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpayroll_lag_3
    ,LAG(mpayroll2, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpayroll2_lag_3
    ,LAG(cpayroll2_trx, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cpayroll2_trx_lag_3
    ,LAG(ccuenta_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccuenta_debitos_automaticos_lag_3
    ,LAG(mcuenta_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcuenta_debitos_automaticos_lag_3
    ,LAG(ctarjeta_visa_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_visa_debitos_automaticos_lag_3
    ,LAG(mttarjeta_visa_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mttarjeta_visa_debitos_automaticos_lag_3
    ,LAG(ctarjeta_master_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_master_debitos_automaticos_lag_3
    ,LAG(mttarjeta_master_debitos_automaticos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mttarjeta_master_debitos_automaticos_lag_3
    ,LAG(cpagodeservicios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cpagodeservicios_lag_3
    ,LAG(mpagodeservicios, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpagodeservicios_lag_3
    ,LAG(cpagomiscuentas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cpagomiscuentas_lag_3
    ,LAG(mpagomiscuentas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mpagomiscuentas_lag_3
    ,LAG(ccajeros_propios_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajeros_propios_descuentos_lag_3
    ,LAG(mcajeros_propios_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcajeros_propios_descuentos_lag_3
    ,LAG(ctarjeta_visa_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_visa_descuentos_lag_3
    ,LAG(mtarjeta_visa_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtarjeta_visa_descuentos_lag_3
    ,LAG(ctarjeta_master_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctarjeta_master_descuentos_lag_3
    ,LAG(mtarjeta_master_descuentos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtarjeta_master_descuentos_lag_3
    ,LAG(ccomisiones_mantenimiento, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccomisiones_mantenimiento_lag_3
    ,LAG(mcomisiones_mantenimiento, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcomisiones_mantenimiento_lag_3
    ,LAG(ccomisiones_otras, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccomisiones_otras_lag_3
    ,LAG(mcomisiones_otras, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcomisiones_otras_lag_3
    ,LAG(cforex, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cforex_lag_3
    ,LAG(cforex_buy, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cforex_buy_lag_3
    ,LAG(mforex_buy, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mforex_buy_lag_3
    ,LAG(cforex_sell, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cforex_sell_lag_3
    ,LAG(mforex_sell, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mforex_sell_lag_3
    ,LAG(ctransferencias_recibidas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctransferencias_recibidas_lag_3
    ,LAG(mtransferencias_recibidas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtransferencias_recibidas_lag_3
    ,LAG(ctransferencias_emitidas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctransferencias_emitidas_lag_3
    ,LAG(mtransferencias_emitidas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mtransferencias_emitidas_lag_3
    ,LAG(cextraccion_autoservicio, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cextraccion_autoservicio_lag_3
    ,LAG(mextraccion_autoservicio, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mextraccion_autoservicio_lag_3
    ,LAG(ccheques_depositados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccheques_depositados_lag_3
    ,LAG(mcheques_depositados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcheques_depositados_lag_3
    ,LAG(ccheques_emitidos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccheques_emitidos_lag_3
    ,LAG(mcheques_emitidos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcheques_emitidos_lag_3
    ,LAG(ccheques_depositados_rechazados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccheques_depositados_rechazados_lag_3
    ,LAG(mcheques_depositados_rechazados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcheques_depositados_rechazados_lag_3
    ,LAG(ccheques_emitidos_rechazados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccheques_emitidos_rechazados_lag_3
    ,LAG(mcheques_emitidos_rechazados, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS mcheques_emitidos_rechazados_lag_3
    ,LAG(tcallcenter, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS tcallcenter_lag_3
    ,LAG(ccallcenter_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccallcenter_transacciones_lag_3
    ,LAG(thomebanking, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS thomebanking_lag_3
    ,LAG(chomebanking_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS chomebanking_transacciones_lag_3
    ,LAG(ccajas_transacciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_transacciones_lag_3
    ,LAG(ccajas_consultas, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_consultas_lag_3
    ,LAG(ccajas_depositos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_depositos_lag_3
    ,LAG(ccajas_extracciones, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_extracciones_lag_3
    ,LAG(ccajas_otras, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ccajas_otras_lag_3
    ,LAG(catm_trx, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS catm_trx_lag_3
    ,LAG(matm, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS matm_lag_3
    ,LAG(catm_trx_other, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS catm_trx_other_lag_3
    ,LAG(matm_other, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS matm_other_lag_3
    ,LAG(ctrx_quarter, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS ctrx_quarter_lag_3
    ,LAG(tmobile_app, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS tmobile_app_lag_3
    ,LAG(cmobile_app_trx, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS cmobile_app_trx_lag_3
    ,LAG(Master_delinquency, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_delinquency_lag_3
    ,LAG(Master_status, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_status_lag_3
    ,LAG(Master_mfinanciacion_limite, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mfinanciacion_limite_lag_3
    ,LAG(Master_Fvencimiento, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_Fvencimiento_lag_3
    ,LAG(Master_Finiciomora, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_Finiciomora_lag_3
    ,LAG(Master_msaldototal, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_msaldototal_lag_3
    ,LAG(Master_msaldopesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_msaldopesos_lag_3
    ,LAG(Master_msaldodolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_msaldodolares_lag_3
    ,LAG(Master_mconsumospesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mconsumospesos_lag_3
    ,LAG(Master_mconsumosdolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mconsumosdolares_lag_3
    ,LAG(Master_mlimitecompra, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mlimitecompra_lag_3
    ,LAG(Master_madelantopesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_madelantopesos_lag_3
    ,LAG(Master_madelantodolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_madelantodolares_lag_3
    ,LAG(Master_fultimo_cierre, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_fultimo_cierre_lag_3
    ,LAG(Master_mpagado, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mpagado_lag_3
    ,LAG(Master_mpagospesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mpagospesos_lag_3
    ,LAG(Master_mpagosdolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mpagosdolares_lag_3
    ,LAG(Master_fechaalta, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_fechaalta_lag_3
    ,LAG(Master_mconsumototal, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mconsumototal_lag_3
    ,LAG(Master_cconsumos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_cconsumos_lag_3
    ,LAG(Master_cadelantosefectivo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_cadelantosefectivo_lag_3
    ,LAG(Master_mpagominimo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Master_mpagominimo_lag_3
    ,LAG(Visa_delinquency, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_delinquency_lag_3
    ,LAG(Visa_status, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_status_lag_3
    ,LAG(Visa_mfinanciacion_limite, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mfinanciacion_limite_lag_3
    ,LAG(Visa_Fvencimiento, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_Fvencimiento_lag_3
    ,LAG(Visa_Finiciomora, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_Finiciomora_lag_3
    ,LAG(Visa_msaldototal, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_msaldototal_lag_3
    ,LAG(Visa_msaldopesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_msaldopesos_lag_3
    ,LAG(Visa_msaldodolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_msaldodolares_lag_3
    ,LAG(Visa_mconsumospesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mconsumospesos_lag_3
    ,LAG(Visa_mconsumosdolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mconsumosdolares_lag_3
    ,LAG(Visa_mlimitecompra, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mlimitecompra_lag_3
    ,LAG(Visa_madelantopesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_madelantopesos_lag_3
    ,LAG(Visa_madelantodolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_madelantodolares_lag_3
    ,LAG(Visa_fultimo_cierre, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_fultimo_cierre_lag_3
    ,LAG(Visa_mpagado, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mpagado_lag_3
    ,LAG(Visa_mpagospesos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mpagospesos_lag_3
    ,LAG(Visa_mpagosdolares, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mpagosdolares_lag_3
    ,LAG(Visa_fechaalta, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_fechaalta_lag_3
    ,LAG(Visa_mconsumototal, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mconsumototal_lag_3
    ,LAG(Visa_cconsumos, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_cconsumos_lag_3
    ,LAG(Visa_cadelantosefectivo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_cadelantosefectivo_lag_3
    ,LAG(Visa_mpagominimo, 3) OVER (PARTITION BY numero_de_cliente ORDER BY foto_mes ASC) AS Visa_mpagominimo_lag_3
FROM competencia_03